context:
  workpath:
  sources:

pipeline:
  input:
    reader:
      type: csv
      filename: 'product.csv'
    # blueprint: path/to/blueprint
  encoder:
    parse:
      nullify: ~
      filter_empty: ~
      unflatten:
        separator: '-'
  actions:
    remove_empty_values:
      action: modify
      modifier: 'remove_empty'
    remove_unwanted:
      action: remove
      keys: [categories, enabled, family, parent, groups]
    copy_identifier:
      action: copy
      from: 'sku'
      to: 'id'
    reseat_id:
      action: reseat
      from: ['id']
      to: '@attributes'
    reseat_all:
      action: reseat
      from: all
      to: Product
  output:
    writer:
      type: xml
      filename: 'new_product.xml'
      options:
        start:
          PutRequest:
            '@attributes':
              xmlns: urn:xmlns:nedfox-retail3000api-com:putrequest
              version: '6.0'
        container: Products
